import { PAGE } from "../styles/tokens.js";
import {
  BrandStrip,
  BackLink,
  PageFooter,
  H1,
  Lede,
  H2,
  P,
  Strong,
  Link,
} from "./longform.jsx";

const REPO = "https://github.com/NavyDevilDoc/rag-advisor";

export default function Terms() {
  return (
    <div style={PAGE}>
      <BrandStrip />
      <article style={{ maxWidth: 620, margin: "0 auto" }}>
        <BackLink />
        <H1>Terms of Use</H1>
        <Lede>
          Last updated: 2026-05-14. By using this tool, you agree to the
          following. It's a short list — please read it.
        </Lede>

        <H2>No warranty</H2>
        <P>
          This tool is provided <Strong>as-is</Strong>, with no warranty of any
          kind. The recommendations it produces are opinions generated by a
          hand-tuned scoring engine plus an LLM evaluation layer — not
          measured outputs from running your data through an actual RAG
          pipeline. The author makes no claim that the recommendation will be
          correct for your specific situation.
        </P>

        <H2>Advisory only</H2>
        <P>
          The output of this tool is informational, not professional advice.{" "}
          <Strong>
            Don't base a $50,000 architecture decision purely on a 12-question
            wizard.
          </Strong>{" "}
          Use this tool to orient yourself, generate questions, and structure
          a conversation with your team. Then prototype, measure, and decide.
        </P>

        <H2>AI-generated content</H2>
        <P>
          The two AI-written paragraphs on the results page are produced by
          Anthropic's Claude. Generated text can be incorrect, incomplete, or
          misleading. Treat them as starting points for investigation, not
          authoritative recommendations. See the{" "}
          <Link href="/methodology">methodology page</Link> for what the AI
          layer does and doesn't do.
        </P>

        <H2>No service-level agreement</H2>
        <P>
          This is a personal project. The site may go down, change behavior,
          or be discontinued without notice. Don't build production
          dependencies on it. If you need persistent access, fork and self-host.
        </P>

        <H2>Liability</H2>
        <P>
          The author is not liable for any damages arising from use of this
          tool, direct or indirect. If you make a bad decision based on the
          recommendation, that's on you.
        </P>

        <H2>Open source</H2>
        <P>
          The full source is available at{" "}
          <Link href={REPO}>github.com/NavyDevilDoc/rag-advisor</Link> under the{" "}
          <Link href={`${REPO}/blob/main/LICENSE`}>MIT License</Link>. You're
          welcome to fork, modify, and redeploy.
        </P>

        <H2>Changes</H2>
        <P>
          These terms may change over time. The current version always lives at{" "}
          <Link href="/terms">/terms</Link>. Material changes will be noted by
          updating the date at the top.
        </P>

        <PageFooter />
      </article>
    </div>
  );
}
